general:
  cloudflare_account_id: "Cloudflare AccountID"
  environment: "Deployment Environment"

cloudflare:
  api_key: "Cloudflare API key" # Use CICD to fetch from secret "location"
  email: "Cloudflare Email"
  retries: 5

backend_s3: # I will be adding more options | I am working with minio thus "all skips"
  endpoint: "https://s3endpoint.xyz"
  access_key: "SUPERSECRETKEY"
  secret_key: "SUPERSECRETKEY"
  region: "main"
  bucket: "NAME_OF_BUCKET"
  skip_region_validation: True
  skip_metadata_api_check: True
  skip_credentials_validation: True
  force_path_style: True

zones:
  - name: "example.xyz"
    create_zone: # True or False (If True, CDK will create DNS zone, if False it will use existing
    records:
      - name: "test"
        type: "CNAME"
        value: "www.google.com"
      - name: "test2"
        type: "A"
        value: "1.1.1.1"
        #proxied: False | Optional values
        #ttl: 60 | Optional values
        #allow_overwrite: False | Optional values
        #comment: "test comment" | Optional values
        #priority: 2 | Optional values